-- Name: Wen Qiu
-- Date: May 30, 2019
-- Section: CSE 154 AJ
-- This sql file inserts the remaining data into the inventory table for the
-- Adapted Toy Inventory.

INSERT INTO inventory (item, function, total, adapted, unadapted, broken, other, donated, available, image)
VALUES
('Flapping Yellow Duck', 'Lights , Sound , Motion', 3, 1, 2, 0, 0, 1, 0, ''),
('Fiber Optic Lamp', 'Lights', 6, 2, 4, 0, 0, 2, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/fiber_optic_lamp.jpg'),
('Frozen Olaf Plush', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/01/DSC_0199.jpg'),
('Colorful Bubbles', 'Motion', 2, 2, 0, 0, 0, 2, 0, ''),
('Bubble blowout', 'Motion', 1, 1, 0, 0, 0, 1, 0, ''),
('My Dancing Penguin Pet', 'Sound , Motion', 1, 1, 0, 0, 0, 1, 0, ''),
('Prism Light', 'Lights', 20, 10, 7, 1, 2, 2, 8, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/prism_light.jpg'),
('LED Party Light', 'Lights', 2, 2, 0, 0, 0, 0, 2, ''),
('Giggling Gourmet Stack N Spin Burger', 'Sound , Motion', 6, 4, 0, 2, 0, 1, 3, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/spin_burger.jpg'),
('Uno Attack', 'Motion', 3, 2, 0, 1, 0, 2, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/uno_attack.jpg'),
('Magic Spinning Art Machine', 'Motion', 6, 1, 5, 0, 0, 0, 1, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/spinning_art_machine.jpg'),
('Laugh & Learn My Pretty Learning Lamp', 'Lights , Sound , Motion', 3, 2, 1, 0, 0, 1, 1, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/learning_lamp.jpg'),
('Roll and Learn Turtle', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Press & Crawl Turtle', 'Sound', 1, 1, 0, 0, 0, 1, 0, ''),
('My Pal Scout', 'Lights , Sound', 1, 1, 0, 0, 0, 1, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/01/DSC_0436.jpg'),
('Scout\'s Goodnight Flashlight', 'Lights , Sound', 4, 3, 1, 0, 0, 1, 2, ''),
('Bright Beats BeatBelle DLX', 'Lights , Sound , Motion', 5, 2, 0, 2, 1, 1, 1, ''),
('Dump Truck', 'Lights , Sound , Bump N\' Go', 1, 1, 0, 0, 0, 1, 0, ''),
('Electric Train', 'Lights , Sound , Motion , Bump N\' Go', 10, 9, 0, 0, 1, 1, 8, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/wolvol_train-.jpg'),
('Silly Slides Jumping Dolphin', 'Sound , Motion , Bump N\' Go', 8, 8, 0, 0, 0, 2, 6, ''),
('Jolly Penguin Race', 'Sound , Motion , Bump N\' Go', 8, 3, 3, 2, 0, 2, 1, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/penguin_race.jpg'),
('Bump n Bubbles Robot', 'Motion', 2, 2, 0, 0, 0, 1, 1, ''),
('Steam Train Locomotive', 'Lights , Sound , Motion', 2, 2, 0, 0, 0, 2, 0, ''),
('My Pal Violet', 'Sound', 1, 1, 0, 0, 0, 0, 1, ''),
('Race and Chase Fire Truck', 'Motion', 1, 1, 0, 0, 0, 1, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/race_and_chase_fire_truck.jpg'),
('Octopus Party Machine', 'Motion', 2, 2, 0, 0, 0, 2, 0, ''),
('Fridge Phonics Magnet Set', 'Sound', 1, 1, 0, 0, 0, 1, 0, ''),
('Take Along Tunes', 'Lights , Sound', 2, 2, 0, 0, 0, 0, 2, ''),
('Rock & Glow Unicorn Toy', 'Lights , Sound , Motion', 1, 1, 0, 0, 0, 1, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/unicorn.jpg'),
('Laugh & Learn Smart Stages Piggy Bank', 'Lights , Sound', 1, 1, 0, 0, 0, 1, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/piggy_bank.jpg'),
('CAT Buildin\' Crew Lightning Pete Bulldozer', 'Lights , Sound , Motion', 1, 0, 0, 1, 0, 0, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/bulldozer.jpg'),
('Shaking School Bus', 'Lights , Sound , Motion', 2, 1, 1, 0, 0, 1, 0, ''),
('Take Along Carrier Toy Bar', 'Lights , Sound', 1, 0, 0, 1, 0, 0, 0, ''),
('Spin and Learn Color Flashlight', 'Lights , Sound', 3, 0, 1, 2, 0, 1, -1, ''),
('Count and Wobble Cody', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Bright Beats Dance & Move Beat BowWow', 'Lights , Sound , Motion', 4, 2, 0, 2, 0, 0, 2, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/bowwow.jpg'),
('Cartoon ChooChoo', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Bubble train', 'Lights , Sound , Motion', 2, 1, 1, 0, 0, 0, 1, ''),
('Bluetooth Speakers', 'Sound', 2, 0, 2, 0, 0, 0, 0, ''),
('Peak-A-Boo Elmo', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Smart Speedster Sis', 'Lights , Sound', 2, 0, 2, 0, 0, 0, 0, ''),
('Piper My Dancing Penguin', 'Lights , Sound , Motion', 4, 1, 2, 1, 0, 0, 1, ''),
('Night Light Moon Star Projector 360 Degree Rotation', 'Lights , Sound', 1, 0, 0, 1, 0, 0, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/360_rotation.jpg'),
('Bumping Car', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Mr Bubble Super Double Blower Party Machine', 'Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Kitchen Appliance Toy Blender', 'Lights , Sound , Motion', 1, 0, 0, 1, 0, 0, 0, ''),
('Nursery Rhyme Elmo', 'Sound', 1, 1, 0, 0, 0, 0, 1, ''),
('Press & Glow Spinner', 'Lights , Sound , Motion', 6, 0, 5, 1, 0, 0, 0, ''),
('Rock Light and Roll', 'Lights , Sound', 2, 1, 0, 1, 0, 1, 0, ''),
('Cowy the Bowling Ball', 'Lights , Sound', 1, 0, 0, 0, 1, 0, 0, ''),
('Light N Go Movin\' Lights Monkey', 'Lights , Sound , Motion , Bump N\' Go', 1, 0, 0, 0, 1, 0, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/moving_lights_monkey.jpg'),
('Talking ABC Elmo', 'Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Peek-A-Boo Bear', 'Sound', 2, 1, 1, 0, 0, 0, 1, ''),
('Musical Dancing Goose', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Bright Beats BestBelle-ito', 'Lights , Sound , Motion', 1, 0, 0, 0, 1, 0, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/beatbelle.jpg'),
('Hip Dog', 'Sound , Motion', 2, 0, 2, 0, 0, 0, 0, ''),
('Octopus Orchestra', 'Lights , Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Mother Goose', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Flappy the Elephant', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Dalton the Dragon', 'Sound', 1, 1, 0, 0, 0, 0, 1, ''),
('Gazillion Tons and Tons of Bubble Fun', 'Lights , Sound , Motion', 1, 0, 0, 1, 0, 0, 0, ''),
('2435 Prisma Light Kaleidoscope Light Show Projector', 'Lights', 6, 5, 0, 1, 0, 1, 4, ''),
('Willie Jumpin\' Duck', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Animated Happy Birthday Teddy Bear', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Later Gator', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Baby Beats Monkey Drum', 'Lights , Sound', 1, 0, 0, 1, 0, 0, 0, ''),
('Singing Paddy Frog', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Pull and Sign Puppy', 'Lights , Sound', 1, 0, 0, 1, 0, 0, 0, ''),
('Giddy Banana Monkey', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Peak A Boo Daisy', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Tyrannosaurus Rex Dinosaur Toy', 'Lights , Sound , Motion', 2, 0, 2, 0, 0, 0, 0, ''),
('Spinning Lights Learning Hippo', 'Lights , Sound', 2, 1, 0, 1, 0, 1, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/learning_hippo.jpg'),
('Dance Robot Electronic', 'Lights , Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Discover & Play Piano Toy', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('PAW Patrol Motorized Bubble Machine', 'Sound , Motion', 6, 4, 1, 0, 1, 0, 4, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/bubble_machine.jpg'),
('Sesame Street Talking 123 Cookie Monster Figure', 'Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Carrera Go Race Track', 'Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Chase N Go Ball Popper', 'Sound , Motion', 2, 0, 1, 1, 0, 0, 0, ''),
('Massage Mate', 'Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Baby Lil\' Critters Soothing Starlight Polar Bear', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Magic Moves Electronic Wand', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Laugh and Learn Learning Lantern', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Cat', 'Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Musical Floppy Eared Dog', 'Sound , Motion', 2, 1, 1, 0, 0, 0, 1, ''),
('Crackin Up Coco', 'Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Plush Dog', 'Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Chatty Charlie the Barkin Beagle', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Popper', 'Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Rockin Birthday', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Fubbles Bubble blastin machine', 'Motion', 2, 1, 0, 1, 0, 1, 0, ''),
('Portable RGB Disco Ball', 'Lights , Motion', 1, 0, 0, 1, 0, 0, 0, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/disco_ball.jpg'),
('Chuckle Ball', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Twister Light', 'Lights', 1, 1, 0, 0, 0, 1, 0, ''),
('Wiggle & Crawl Ball', 'Lights , Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Rockin Flower', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Candylicious Bubble Machine and Play Set', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Machine Automatic Dolphin Bubble Blower', 'Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Road Rippers', 'Lights , Sound , Motion , Bump N\' Go', 1, 1, 0, 0, 0, 1, 0, ''),
('Splash the Singing Turtle', 'Lights , Sound', 1, 0, 0, 1, 0, 0, 0, ''),
('My White Pony', 'Lights , Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Automatic Bubble Machine', 'Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Keys to Discover Piano Toy', 'Lights , Sound', 1, 1, 0, 0, 0, 0, 1, ''),
('Cute Mini Fire Truck', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Explore and Crawl Learning Cub', 'Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Ocean Orchestra', 'Lights , Sound , Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Road Rippers Wheelie Bikes', 'Motion', 1, 1, 0, 0, 0, 0, 1, 'http://depts.washington.edu/adaptuw/wordpress/wp-content/uploads/2019/05/wheelie_bike.jpg'),
('Electronic Baseball Pitching Machine', 'Motion', 1, 0, 1, 0, 0, 0, 0, ''),
('Smart Swing Penguin', 'Lights , Sound , Motion', 1, 1, 0, 0, 0, 1, 0, ''),
('Having a Ball Spin & Giggle Puppy', 'Sound , Motion', 1, 0, 0, 1, 0, 0, 0, ''),
('Construction Vehicle', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('Mozart Magic Cube', 'Lights , Sound', 1, 0, 1, 0, 0, 0, 0, ''),
('The Good Dinosaur', 'Sound , Motion', 1, 1, 0, 0, 0, 0, 1, ''),
('Color Play Drum', 'Lights , Sound', 1, 1, 0, 0, 0, 0, 1, ''),
('Kumi’s Beat Box', 'Lights , Sound', 5, 4, 1, 0, 0, 2, 2, ''),
('Car Trax', 'Lights , Motion', 2, 0, 1, 1, 0, 0, 0, ''),
('Flapping yellow duck', 'Lights , Sound , Motion', 3, 1, 2, 0, 0, 1, 0, ''),
('Fishing Games', 'Sound , Motion', 2, 0, 2, 0, 0, 0, 0, ''),
('Movin Lights Monkey', 'Lights , Sound , Motion', 3, 3, 0, 0, 0, 0, 3, '');
